litellm_settings:
  drop_params: true
  force_model_max_tokens: true

model_list:
  - model_name: "claude-opus-4-5-20251101"
    litellm_params:
      model: openai/dashscope/qwen-turbo-2025-04-28
      api_base: https://api.edenai.run/v3/llm
      api_key: "os.environ/EDEN_AI_API_KEY"
    model_info:
      max_tokens: 16384
      
  - model_name: "claude-3-5-sonnet-20240620"
    litellm_params:
      model: openai/dashscope/qwen-turbo-2025-04-28
      api_base: https://api.edenai.run/v3/llm
      api_key: "os.environ/EDEN_AI_API_KEY"
    model_info:
      max_tokens: 16384

  - model_name: "*"
    litellm_params:
      model: openai/dashscope/qwen-turbo-2025-04-28
      api_base: https://api.edenai.run/v3/llm
      api_key: "os.environ/EDEN_AI_API_KEY"
